name: BERT-NRMS
meta:
  item: Bert
  user: Attention
  predictor: Dot
config:
  use_item_content: true
  item_page_size: ${item_page_size}$
  item_hidden_size: ${item_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
    weights_dir: data/${data.name}/bert-${llm_ver}-split
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
