name: BERT-MINER
meta:
  item: Bert
  user: PolyAttention
  predictor: MINER
config:
  use_neg_sampling: true
  use_item_content: true
  item_page_size: ${item_page_size}$
  item_hidden_size: ${item_hidden_size}$
  hidden_size: ${hidden_size}$
  page_size: 512
  neg_count: 4
  item_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
    weights_dir: data/${data.name}/bert-${llm_ver}-split
  user_config:
    num_context_codes: 32
    context_code_dim: 256
    inputer_config:
      use_cls_token: false
      use_sep_token: false
