name: BST.NRL-D${model.config.hidden_size}
config:
  use_item_content: false
  hidden_size: 64
  neg_count: 4
  user_config:
    num_attention_heads: 4
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: false
