name: FinalMLP
meta:
  item: Pooling
  user: Pooling
  predictor: FinalMLP
config:
  use_item_content: true
  hidden_size: 64
  item_config:
    flatten: false
    max_pooling: false
  user_config:
    flatten: false
    max_pooling: false