name: DIN
meta:
  item: Pooling
  user: NullConcat
  predictor: DIN
config:
  use_neg_sampling: false
  use_news_content: true
  hidden_size: 64
  news_config:
    flatten: false
    max_pooling: false
  user_config:
    flatten: false
    max_pooling: false
  predictor_config:
    dnn_hidden_units: [ 1000, 1000, 1000 ]
    dnn_activations: ReLU
    attention_hidden_units: [ 64 ]
    attention_dropout: 0.1
    net_dropout: 0.1
    batch_norm: false
    din_use_softmax: false
