name: FancyDCN
meta:
  item: CNN
  user: Ada
  predictor: DCN
config:
  use_neg_sampling: true
  use_item_content: true
  hidden_size: ${hidden_size}$
  embed_hidden_size: ${embed_hidden_size}$
  neg_count: 4
  item_config:
    dropout: 0.1
    kernel_size: 3
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
  predictor_config:
    dnn_hidden_units: [ 500, 500, 500 ]
    dnn_activations: ReLU
    dnn_dropout: 0.1
    dnn_batch_norm: false
    cross_num: 3
