name: SemanticMix
meta:
  item: SCSimple
  user: SCFlatten
  predictor: SemanticMix
config:
  use_neg_sampling: false
  use_item_content: true
  cache_activate: false
  hidden_size: ${hidden_size}$
  embed_hidden_size: ${embed_hidden_size}$
  item_config: {}
  user_config: {}
  predictor_config:
    base_predictor: DCN
    base_predictor_config:
      dnn_hidden_units: [ 1000, 1000, 1000 ]
      dnn_activations: ReLU
      dnn_dropout: 0.1
      dnn_batch_norm: false
      cross_num: 3
