name: LLAMA-NAML
meta:
  item: Llama
  user: Ada
  predictor: Dot
config:
  use_neg_sampling: true
  use_item_content: true
  item_page_size: ${item_page_size}$
  item_hidden_size: ${embed_hidden_sijze}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: /home/data1/qijiong/llama-${llm_ver}
    layer_split: ${layer}$
    lora: ${lora}$
    weights_dir: /home/data4/qijiong/Data/Lego/${data.name}/llama-${llm_ver}-split
  user_config:
    num_attention_heads: 12
    inputer_config:
      use_cls_token: false
      use_sep_token: false
