name: LLAMA-NRMS
meta:
  item: Llama
  user: Attention
  predictor: Dot
config:
  use_neg_sampling: true
  use_item_content: true
  item_page_size: ${item_page_size:128}$
  item_hidden_size: 4096
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    tune_from: ${tune_from}$
    use_lora: ${use_lora:false}$
    lora_r: ${lora_r:null}$
    lora_alpha: ${lora_alpha:null}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
  user_config:
    num_attention_heads: ${num_user_heads:8}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
