name: LLAMA-Fastformer
meta:
  item: Llama
  user: Fastformer
  predictor: Dot
config:
  use_item_content: true
  item_page_size: ${item_page_size}$
  item_hidden_size: ${item_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: /home/data1/qijiong/llama-${llm_ver}
    layer_split: ${layer}$
    lora: ${lora}$
    weights_dir: data/${data.name}/llama-${llm_ver}-split
  user_config:
    num_attention_heads: 16
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false
