name: PNN
meta:
  user: Pooling
  predictor: PNN
config:
  use_neg_sampling: false
  use_item_content: false
  hidden_size: 64
  user_config:
    flatten: false
    max_pooling: false
  predictor_config:
    dnn_hidden_units: [ 500, 500, 500 ]
    dnn_activations: ReLU
    dnn_dropout: 0.1
    dnn_batch_norm: false