name: DCN.E2E-USER
meta:
  user: Transformer
  predictor: DCN
config:
  use_neg_sampling: false
  use_item_content: false
  hidden_size: ${hidden_size}$
  user_config:
    num_attention_heads: 8
    num_hidden_layers: 6
    inputer_config:
      use_cls_token: false
      use_sep_token: false
  predictor_config:
    dnn_hidden_units: [ 1000, 1000, 1000 ]
    dnn_activations: ReLU
    dnn_dropout: 0.1
    dnn_batch_norm: false
    cross_num: 3
