name: FinalMLP.Semantic-Item
meta:
  item: Transformer
  user: Transformer
  predictor: FinalMLP
config:
  use_neg_sampling: false
  use_item_content: true
  hidden_size: ${hidden_size}$
  embed_hidden_size: ${embed_hidden_size}$
  item_config:
    num_attention_heads: 8
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false
  user_config:
    num_attention_heads: 8
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false
