name: prec-token
embeddings:
  -
    vocab_name: english
    vocab_type: numpy
    path: transfer/PREC-MINDsmall-L3H4E64/eng_embeds.npy
    frozen: true
  - vocab_name: cat
    vocab_type: numpy
    path: transfer/PREC-MINDsmall-L3H4E64/cat_embeds.npy
    frozen: true