name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}-Trend
log: ${exp.dir}/exp.log
mode: test
load:
  save_dir: ../${embed.name}-train_test-Trend
  epochs: "list(range(${epochs}))"
  model_only: true
  strict: true
  wait: false
store:
  metric: NDCG@5
  maximize: true
  top: 1
  early_stop: ${patience}$
  interval: 1
policy:
  epoch_start: ${epoch_start}$
  epoch: 50
  lr: ${lr}$
  news_lr: ${news_lr}$
  freeze_emb: false
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10
  - Recall@1
  - Recall@5
  - Recall@10