name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_get_user_embedding
load:
  save_dir: null
  epochs: null
  model_only: true
  strict: true
  wait: false
policy:
  pin_memory: false
  batch_size: ${batch_size}$
  device: gpu
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10