name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: ${load_path}$
  epochs: null
  model_only: true
  strict: true
  wait: false
store:
  top: 1
  early_stop: ${patience}$
  metric: GAUC
  maximize: true
policy:
  epoch_start: ${epoch_start}$
  epoch: 50
  lr: ${lr}$
  item_lr: ${item_lr}$
  freeze_emb: false
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10