name: BERT-Fastformer.VER${llm_ver}.D${model.config.hidden_size}.L${model.config.item_config.layer_split}.Lora${model.config.item_config.lora}
meta:
  item: Bert
  user: Fastformer
  predictor: Dot
config:
  use_item_content: true
  use_neg_sampling: true
  use_fast_eval: ${fast_eval}$
  max_item_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
    weights_dir: data/${data.name}/bert-${llm_ver}-split
  user_config:
    num_attention_heads: 16
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false
