name: PLMNR-NRMS.D${model.config.hidden_size}
meta:
  item: Transformer
  user: Attention
  predictor: Dot
config:
  use_item_content: true
  use_neg_sampling: true
  hidden_size: 64
  neg_count: 4
  item_config:
    num_attention_heads: 8
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
